### ISSUE TITLE
关于micro-video数据集缺失特征数据（visual_feature_64）

### ISSUE THREAD

**Issue by MrShouxingMa** [Linxyhaha/TDRO#2]
作者您好，当我尝试运行micro-video数据集时，发现您提供的数据集缺失visual_feature_64数据文件，请问您可以上传缺失的视觉特征数据吗？

**Comment by Linxyhaha** [comment]
你好，micro-video数据集的两个特征文件可以通过https://drive.google.com/drive/folders/1BHpjL4T7CebzRDk10eknL4NSGCdOCxk-?usp=sharing 来获取。

**Comment by MrShouxingMa** [comment]
感谢感谢
